sudo: required
services:
  - docker

before_install:
  -  docker build -t anvithaprabhu8/docker-react -f dockerfile.dev . 

script:
  - docker run -e CI=true  anvithaprabhu8/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "may1"
  env: "may1-env"
  bucket_name: "elasticbeanstalk-us-east-1-058264353440"
  bucket_path: "may1"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"